<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" />
    <PackageReference Include="Microsoft.Agents.AI.AzureAI" />
    <PackageReference Include="Microsoft.Agents.AI.Declarative" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="System.ClientModel" />
  </ItemGroup>

</Project>
